---
version: "3"
services:
  cric:
    image: sraj1/paytmcric:v1
    ports:
      - 8002:80
    deploy:
      - replicas: 2
  bill:
    image: sraj1/paytmbill:v1
    ports:
      - 8003:80
    deploy:
      - replicas: 2
